// <auto-generated />
using System;
using Diger.TramitesEstado.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diger.TramitesEstado.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.AcuerdoReunion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Compromiso")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateOnly?>("FechaCumplimiento")
                        .HasColumnType("date");

                    b.Property<string>("NotaSeguimiento")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Plazo")
                        .HasColumnType("date");

                    b.Property<string>("Responsable")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ReunionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SeguimientoActualizadoEl")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeguimientoActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("Plazo");

                    b.HasIndex("ReunionId");

                    b.ToTable("AcuerdosReunion", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Asistente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoRegistro")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Correo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Departamento")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Institucion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("RegistradoEl")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReunionId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("ReunionId");

                    b.ToTable("Asistentes", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.CategoriaTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriasTicket", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Correo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("InstitucionId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Institucion");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("Nombre");

                    b.ToTable("Contactos", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.DocumentoInterno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<string>("Obs")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("DocumentosInternos", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.DocumentoSolicitado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<bool>("Recibido")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Url")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("DocumentosSolicitados", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Expediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Analista")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ContactoCargo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactoCorreo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactoNombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactoTel")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescProceso")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("DirSede")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DocsAdicionales")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EstadoExpediente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EstadoLevantamiento")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly?>("FechaApertura")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaValidacion")
                        .HasColumnType("date");

                    b.Property<int?>("FuncionariosDig")
                        .HasColumnType("int");

                    b.Property<string>("InfraAcomp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InfraDcDisp")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("InfraDcModalidad")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("InfraDcObs")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("InfraDcVirt")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("InfraDcVirtOtro")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("InfraPersonal")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("InfraPersonalTI")
                        .HasColumnType("int");

                    b.Property<string>("InfraPlan")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("InfraRespSol")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("InstitucionId")
                        .HasColumnType("int");

                    b.Property<string>("NumActa")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("NumFuncionarios")
                        .HasColumnType("int");

                    b.Property<int>("NumTramitesProd")
                        .HasColumnType("int");

                    b.Property<string>("ObsExpediente")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ObsFlujo")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ObsLegal")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ObsLevantamiento")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ObsModelo")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OrigenExternoId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TiempoDig")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TiempoNorma")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TiempoObservado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidadoDiger")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ValidadoInst")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("VolumenAnual")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EstadoExpediente");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("OrigenExternoId")
                        .IsUnique()
                        .HasFilter("[OrigenExternoId] IS NOT NULL");

                    b.ToTable("Expedientes", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.ExpedienteEtapaAvance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<string>("SubId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TramiteIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId", "TramiteIndex", "SubId")
                        .IsUnique();

                    b.ToTable("ExpedienteEtapaAvances", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.ExpedienteSeccionEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<string>("Nota")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Seccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("ExpedienteSecciones", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.ExpedienteTramite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alcance")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("AlcanceObs")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("AreaResponsable")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Dirigido")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DocEntregado")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("EmailTramite")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<string>("Horario")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Modalidad")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NombreCorto")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NombreTramite")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PagoBanco")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PagoCuenta")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PlazoLegal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Tercero")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TgrInst")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TgrMonto")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("TgrRubro")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TiempoReal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TramiteIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId", "TramiteIndex");

                    b.ToTable("ExpedienteTramites", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.FlujoNodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DocEmitido")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Obs")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("RetornoA")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tiempo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TramiteIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId", "TramiteIndex", "Fase");

                    b.ToTable("FlujoNodos", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.FundamentoLegal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Articulos")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<string>("Instrumento")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Obs")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("FundamentosLegales", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.InfraChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Obs")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Requisito")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("InfraChecklist", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.InfraCondicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("InfraCondiciones", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.InfraPerfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("InfraPerfiles", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Institucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Instituciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "CONVIVIENDA"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "COPECO"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "SIT"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "IHADFA"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "BANHPROVI"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "INPREUNAH"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "CNBS"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Nombre = "INPREMA"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Nombre = "IHTT"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Nombre = "SEN"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Nombre = "CONSUCOOP"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Nombre = "CONATEL"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Nombre = "IHCINE"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Nombre = "SAG"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Nombre = "SECAPPH"
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            Nombre = "SRECI"
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            Nombre = "SERNA"
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            Nombre = "SGJD"
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            Nombre = "CANATURH / IHT"
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            Nombre = "IP"
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            Nombre = "SENASA"
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            Nombre = "SESAL"
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            Nombre = "FOSOVI"
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            Nombre = "IHT"
                        });
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Reunion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Compromisos")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Contenido")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("Convocados")
                        .HasColumnType("int");

                    b.Property<int?>("CreadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desarrollo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocsRecursos")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Duracion")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("EpCargo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EpCorreo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EpNombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EpTel")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("EsCapacitacionPlataforma")
                        .HasColumnType("bit");

                    b.Property<string>("FacCargo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FacCorreo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FacNombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Foto1Desc")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Foto1Url")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Foto2Desc")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Foto2Url")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Hora")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Institucion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("InstitucionId")
                        .HasColumnType("int");

                    b.Property<string>("Lugar")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Modalidad")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("NumAsistentes")
                        .HasColumnType("int");

                    b.Property<string>("ObjetivoAgenda")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ObjetivoCap")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OrigenExternoId")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("PctAsistencia")
                        .HasColumnType("int");

                    b.Property<bool>("RegistroAbierto")
                        .HasColumnType("bit");

                    b.Property<Guid>("RegistroToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Satisfaccion")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Tema")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValDiger")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ValInst")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Visibilidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Publica");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("Fecha");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("OrigenExternoId")
                        .IsUnique()
                        .HasFilter("[OrigenExternoId] IS NOT NULL");

                    b.HasIndex("RegistroToken")
                        .IsUnique();

                    b.HasIndex("Visibilidad", "CreadoPorId");

                    b.ToTable("Reuniones", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.RolModuloAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Rol", "Modulo")
                        .IsUnique();

                    b.ToTable("RolModuloAccesos", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.TemaTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorasResolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TemasTicket", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AsignadoA")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("AsignadoAId")
                        .HasColumnType("int");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("CreadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ExpedienteCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institucion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("InstitucionId")
                        .HasColumnType("int");

                    b.Property<string>("NotaResolucion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReportanteCorreo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReportanteNombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ReportanteTelefono")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("TemaId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoAId");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Estado");

                    b.HasIndex("ExpedienteId");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("TemaId");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.TicketAdjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComentarioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("Tamano")
                        .HasColumnType("bigint");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketAdjuntos", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.TicketComentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketComentarios", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.TicketTramite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("Tramite")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("TramiteDefinicionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketTramites", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.TramiteDefinicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstitucionId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId", "Orden");

                    b.ToTable("TramitesDefinicion", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.TramiteRequisito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<string>("Justificacion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Obs")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Requisito")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TramiteIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId", "TramiteIndex");

                    b.ToTable("TramiteRequisitos", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.UsuarioInstitucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstitucionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("UsuarioId", "InstitucionId")
                        .IsUnique();

                    b.ToTable("UsuarioInstituciones", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.UsuarioTema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TemaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.HasIndex("UsuarioId", "TemaId")
                        .IsUnique();

                    b.ToTable("UsuarioTemas", (string)null);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.AcuerdoReunion", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Reunion", null)
                        .WithMany("Acuerdos")
                        .HasForeignKey("ReunionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Asistente", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Reunion", null)
                        .WithMany("Asistentes")
                        .HasForeignKey("ReunionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Contacto", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Institucion", null)
                        .WithMany()
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.DocumentoInterno", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Expediente", null)
                        .WithMany("DocsInternos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.DocumentoSolicitado", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Expediente", null)
                        .WithMany("DocsSolicitados")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Expediente", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Institucion", null)
                        .WithMany()
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.ExpedienteEtapaAvance", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Expediente", null)
                        .WithMany()
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.ExpedienteSeccionEstado", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Expediente", null)
                        .WithMany("Secciones")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.ExpedienteTramite", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Expediente", null)
                        .WithMany("Tramites")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.FlujoNodo", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Expediente", null)
                        .WithMany("Flujos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.FundamentoLegal", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Expediente", null)
                        .WithMany("Legal")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.InfraChecklistItem", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Expediente", null)
                        .WithMany("ChecklistInfra")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.InfraCondicion", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Expediente", null)
                        .WithMany("Condiciones")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.InfraPerfil", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Expediente", null)
                        .WithMany("Perfiles")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Reunion", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Institucion", null)
                        .WithMany()
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.TemaTicket", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.CategoriaTicket", "CategoriaRef")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CategoriaRef");
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AsignadoAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Expediente", null)
                        .WithMany()
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Institucion", null)
                        .WithMany()
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Diger.TramitesEstado.Domain.Entities.TemaTicket", "TemaRef")
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("TemaRef");
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.TicketAdjunto", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Ticket", null)
                        .WithMany("Adjuntos")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.TicketComentario", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Ticket", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.TicketTramite", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Ticket", null)
                        .WithMany("Tramites")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.TramiteDefinicion", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Institucion", null)
                        .WithMany("Tramites")
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.TramiteRequisito", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Expediente", null)
                        .WithMany("Requisitos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.UsuarioInstitucion", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Institucion", null)
                        .WithMany()
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.UsuarioTema", b =>
                {
                    b.HasOne("Diger.TramitesEstado.Domain.Entities.TemaTicket", null)
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diger.TramitesEstado.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Expediente", b =>
                {
                    b.Navigation("ChecklistInfra");

                    b.Navigation("Condiciones");

                    b.Navigation("DocsInternos");

                    b.Navigation("DocsSolicitados");

                    b.Navigation("Flujos");

                    b.Navigation("Legal");

                    b.Navigation("Perfiles");

                    b.Navigation("Requisitos");

                    b.Navigation("Secciones");

                    b.Navigation("Tramites");
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Institucion", b =>
                {
                    b.Navigation("Tramites");
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Reunion", b =>
                {
                    b.Navigation("Acuerdos");

                    b.Navigation("Asistentes");
                });

            modelBuilder.Entity("Diger.TramitesEstado.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Adjuntos");

                    b.Navigation("Comentarios");

                    b.Navigation("Tramites");
                });
#pragma warning restore 612, 618
        }
    }
}
